### ISSUE TITLE
Increase support for uppercase letters

### ISSUE THREAD

**Issue by heennkkee** [mosbth/Anax-oophp#10]
With a simple altering of the foreach that converts your key to lowercase would increase the flexibility for the user. 

```
foreach ($filter as $key) {
            $lowKey = strtolower($key);
            if (isset($callbacks[$lowKey])) {
                $text = call_user_func_array(array($this, $callbacks[$lowKey]), array($text));
            } else {
                throw new Exception("The filter '$filters' is not a valid filter string. Its the key '$key' that is unknown and it does not match a valid callback.");
            }
        }
```

The obvious con would be the minor increase in execution time. 

Another approach would be to arrange a while loop, and only test for lowercase matches if the initial key fails, but [it seems like while is a lot slower than foreach](http://php.net/manual/en/function.each.php#75692) so it's probably just faster to convert every input to lowercase.

**Comment by mosbth** [comment]
Or consider that the user of the class could do `strtolower()`, before calling `CTextFilter`. Thats also one option.

The further development of CTextFilter is done here, in its own repo (used in the phpmvc-course).
https://github.com/mosbth/ctextfilter
