### ISSUE TITLE
makeClickable anonymus function

### ISSUE THREAD

**Issue by Slugg0** [mosbth/Anax-oophp#3]
Maybe I've done something wrong here, but when copying your code and putting it in my Anax, makeClickable creates the link `<a href="active/dir/\'http://link.se\'>http://link.se</a>`

Replacing  
    `function ($matches) {
        return "<a href=\'{$matches[0]}\'>{$matches[0]}</a>";
    },`
with
    `create_function(
        '$matches',
        'return "<a href=\'{$matches[0]}\'>{$matches[0]}</a>";' 
    ),`
solved it for me.

**Comment by mosbth** [comment]
How does your text source look like?

**Comment by mosbth** [comment]
Saw another example, just like this.

> some link http://example.com here

I'll check it up tomorrow. The link seems to be incorrect.

**Comment by Slugg0** [comment]
I made a testprogram of this [Here](http://www.student.bth.se/~stro14/oophp/tester/clicktest/webroot/content.php)

**Comment by mosbth** [comment]
I fixed it by removing \ in the string. Should work in 1.0.1.
