### ISSUE TITLE
Small suggestions, bbcode and nl2br

### ISSUE THREAD

**Issue by Slugg0** [mosbth/Anax-oophp#4]
I know this code is just a base to buid on, but implementing `<code>` in bbcode2html, is really useful in my opinion, since lots of codes are printed in the OOPHP reports.
My suggestion: 

```
function bbcode2html($text) {
$search = array(
    ...
    '/\[c\](.*?)\[\/c\]/is',
    ...
);   
$replace = array(
    ...
    '<code>$1</code>',
    ...
);     
```

Also, auto- creating paragraphs with nl2br would be great. Instead of multiple br-tags, the text is placed in a p-tag.
For example:

```
public function nl2brAndParagraphs($text) {
    $br = nl2br($text);
    $data = preg_replace('/^\s*(?:<br\s*\/?>\s*)*/i', '', $br);
    $data = preg_replace('/\s*(?:<br\s*\/?>\s*)*$/i', '', $data);

    $data = preg_replace('#(?:<br\s*/?>\s*?){2,}#','</p>
    <p>',$data);
    $data = '<p>'.$data.'</p>';
    return $data;
}
```

**Comment by mosbth** [comment]
Its nice suggestions but since its labmaterial I'll leave it as is for now. But I will move this code, for CTextFilter, out of this repo into its own. There is a better place to further add features for the class.

**Comment by mosbth** [comment]
Will be fixed in the new repo for pure development of CTextFilter, feel free to add your own items and make a push request.
https://github.com/mosbth/ctextfilter/issues/2
