### ISSUE TITLE
CTextfilter - doFilter()

### ISSUE THREAD

**Issue by TomasSjosten** [mosbth/Anax-oophp#8]
Expects $filters param to be string currently. I added support for array, which I think was the original idea.

$filter = (is_array($filters)) ? $filters : preg_replace('/\s/', '', explode(',', $filters));

**Comment by mosbth** [comment]
It seems like a good approach to support both. I added it to the repo where I do further development on CTextFilter.
https://github.com/mosbth/ctextfilter/issues/4
